//PROJECTS
export const FORM_PROJECT = 'FORM_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const VALID_FORM = 'VALID_FORM'
export const CURRENT_PROJECT = 'CURRENT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const ERROR_PROJECT = 'ERROR_PROJECT'


//TASK
export const TASK_PROJECT = 'TASK_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const VALID_TASK = 'VALID_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const STATE_TASK = 'STATE_TASK'
export const CURRENT_TASK = 'CURRENT_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const CLEAN_TASK = 'CLEAN_TASK'

//ALERTS
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

//AUHT
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP'
export const ERROR_SIGNUP = 'ERROR_SIGNUP'
export const GET_USER = 'GET_USER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const CLOSE_SESSION = 'CLOSE_SESSION'